media_folder: static/images/uploads
backend:
  repo: cwahlfeldt/waffle-iron
  name: git-gateway
  branch: dev
  api_root: https://api.github.com
  site_domain: localhost
  base_url: https://github.com
  auth_endpoint: auth
  cms_label_prefix: waffle-iron-cms/